### ISSUE TITLE
migrating from 3

### ISSUE THREAD

**Issue by mat813** [daghf/libvmod-saintmode#3]
Hi,

I had this bit of config that worked nicely in varnish 3:

```
        if (beresp.status != 200 && (beresp.status != 404 || req.restarts < 2) ) {
                set beresp.saintmode = 10s;
                return(restart);
        }
```

It would retry all non 200 requests, and retry 404 only twice (because sometime, a backend returns a 404 and it is a lie, but sometime, it is not, so retrying is good, but not too much retrying is needed)

So, right now, I'm doing:

```
        if (beresp.status != 200) {
                saintmode.blacklist(10s);
                return (retry);
        }
```

I don't know where to get the req.restarts from...

**Comment by daghf** [comment]
Hi

What you are looking for is called `beresp.retries`.
